Removing other people's executables, part one.

diff --git a/bin/gtf2bed b/bin/gtf2bed
--- a/bin/gtf2bed
+++ b/bin/gtf2bed
@@ -1,122 +1,124 @@
-#!/bin/bash
+#!/usr/bin/perl
 
-#
-# convert2bed
-# Copyright (C) 2014-2016 Alex Reynolds
-#
-#    This program is free software; you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation; either version 2 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License along
-#    with this program; if not, write to the Free Software Foundation, Inc.,
-#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-#
+# Copyright (c) 2011 Erik Aronesty (erik@q32.com)
+# 
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+# 
+# The above copyright notice and this permission notice shall be included in
+# all copies or substantial portions of the Software.
+# 
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
+# 
+# ALSO, IT WOULD BE NICE IF YOU LET ME KNOW YOU USED IT.
 
-cmd="convert2bed"
-input_format="gtf"
-output_format="bed"
+use Data::Dumper;
+use Getopt::Long;
 
-# general
+my $extended;
+GetOptions("x"=>\$extended);
 
-do_not_sort=false
-max_mem_set=false
-max_mem="2G"
-sort_tmpdir_set=false
-sort_tmpdir="/tmp"
+$in = shift @ARGV;
 
-# format-specific
+my $in_cmd =($in =~ /\.gz$/ ? "gunzip -c $in|" : $in =~ /\.zip$/ ? "unzip -p $in|" : "$in") || die "Can't open $in: $!\n";
+open IN, $in_cmd;
 
-help()
-{
-    ${cmd} --help-gtf
-    exit $1
+while (<IN>) {
+	$gff = 2 if /^##gff-version 2/;
+	$gff = 3 if /^##gff-version 3/;
+	next if /^#/ && $gff;
+
+	s/\s+$//;
+	# 0-chr 1-src 2-feat 3-beg 4-end 5-scor 6-dir 7-fram 8-attr
+	my @f = split /\t/;
+	if ($gff) {
+        # most ver 2's stick gene names in the id field
+		($id) = $f[8]=~ /\bID="([^"]+)"/;
+        # most ver 3's stick unquoted names in the name field
+		($id) = $f[8]=~ /\bName=([^";]+)/ if !$id && $gff == 3;
+	} else {
+		($id) = $f[8]=~ /transcript_id "([^"]+)"/;
+	}
+
+	next unless $id && $f[0];
+
+	if ($f[2] eq 'exon') {
+		die "no position at exon on line $." if ! $f[3];
+        # gff3 puts :\d in exons sometimes
+        $id =~ s/:\d+$// if $gff == 3;
+		push @{$exons{$id}}, \@f;
+		# save lowest start
+		$trans{$id} = \@f if !$trans{$id};
+	} elsif ($f[2] eq 'start_codon') {
+		#optional, output codon start/stop as "thick" region in bed
+		$sc{$id}->[0] = $f[3];
+	} elsif ($f[2] eq 'stop_codon') {
+		$sc{$id}->[1] = $f[4];
+	} elsif ($f[2] eq 'miRNA' ) {
+		$trans{$id} = \@f if !$trans{$id};
+		push @{$exons{$id}}, \@f;
+	}
 }
 
-optspec=":r:m:dh-:"
-while getopts "$optspec" optchar; do
-    case "${optchar}" in
-        -)
-            case "${OPTARG}" in
-                sort-tmpdir)
-                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
-                    sort_tmpdir=${val}
-                    sort_tmpdir_set=true
-                    ;;
-                sort-tmpdir=*)
-                    val=${OPTARG#*=}
-                    sort_tmpdir=${val}
-                    sort_tmpdir_set=true
-                    ;;
-                max-mem)
-                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
-                    max_mem=${val}
-                    max_mem_set=true
-                    ;;
-                max-mem=*)
-                    val=${OPTARG#*=}
-                    max_mem=${val}
-                    max_mem_set=true
-                    ;;
-                help)
-                    val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
-                    #echo "Parsing option: '--${OPTARG}', value: '${val}'" >&2;
-                    help 0
-                    ;;
-                help=*)
-                    val=${OPTARG#*=}
-                    opt=${OPTARG%=$val}
-                    #echo "Parsing option: '--${opt}', value: '${val}'" >&2
-                    help 0
-                    ;;
-                do-not-sort)
-                    do_not_sort=true
-                    ;;
-                help-gtf)
-                    help 0
-                    ;;
-                *)
-                    help 1
-                    #if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then echo "Unknown option --${OPTARG}" >&2; fi
-                    ;;
-            esac;;
-        r)
-            sort_tmpdir=${OPTARG}
-            sort_tmpdir_set=true
-            ;;
-        m)
-            max_mem=${OPTARG}
-            max_mem_set=true
-            ;;
-        d)
-            do_not_sort=true
-            ;;
-        h)
-            help 0
-            ;;
-        *)
-            help 1
-            #if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then echo "Non-option argument: '-${OPTARG}'" >&2; fi
-            ;;
-    esac
-done
+for $id ( 
+	# sort by chr then pos
+	sort {
+		$trans{$a}->[0] eq $trans{$b}->[0] ? 
+		$trans{$a}->[3] <=> $trans{$b}->[3] : 
+		$trans{$a}->[0] cmp $trans{$b}->[0]
+	} (keys(%trans)) ) {
+		my ($chr, undef, undef, undef, undef, undef, $dir, undef, $attr, undef, $cds, $cde) = @{$trans{$id}};
+        my ($cds, $cde);
+        ($cds, $cde) = @{$sc{$id}} if $sc{$id};
 
-# base options
+		# sort by pos
+		my @ex = sort {
+			$a->[3] <=> $b->[3]
+		} @{$exons{$id}};
 
-options="--input=${input_format} --output=${output_format}"
+		my $beg = $ex[0][3];
+		my $end = $ex[-1][4];
+		
+		if ($dir eq '-') {
+			# swap
+			$tmp=$cds;
+			$cds=$cde;
+			$cde=$tmp;
+			$cds -= 2 if $cds;
+			$cde += 2 if $cde;
+		}
 
-# general
+		# not specified, just use exons
+		$cds = $beg if !$cds;
+		$cde = $end if !$cde;
 
-if [ "${max_mem_set}" = true ]; then options="${options} --max-mem=${max_mem}"; fi
-if [ "${sort_tmpdir_set}" = true ]; then options="${options} --sort-tmpdir=${sort_tmpdir}"; fi
-if [ "${do_not_sort}" = true ]; then options="${options} --do-not-sort"; fi
+		# adjust start for bed
+		--$beg; --$cds;
+	
+		my $exn = @ex;												# exon count
+		my $exst = join ",", map {$_->[3]-$beg-1} @ex;				# exon start
+		my $exsz = join ",", map {$_->[4]-$_->[3]+1} @ex;			# exon size
 
-# format-specific
+        my $gene_id;
+        my $extend = "";
+        if ($extended) {
+    	    ($gene_id) = $attr =~ /gene_name "([^"]+)"/;
+    	    ($gene_id) = $attr =~ /gene_id "([^"]+)"/ unless $gene_id;
+            $extend="\t$gene_id";
+        }
+		# added an extra comma to make it look exactly like ucsc's beds
+		print "$chr\t$beg\t$end\t$id\t0\t$dir\t$cds\t$cde\t0\t$exn\t$exsz,\t$exst,$extend\n";
+}
 
-${cmd} ${options} - <&0
+
+close IN;
